<footer>
    <div class="container">
        <div class="row my-3">
            <div class="col-sm-12">
                <div class="text-center">
                    <h1 class="mb-0">MAXCAPE</h1>
                </div>

                <div class="d-flex text-center mx-auto" style="max-width:700px;">
                    <div class="p-2 flex-fill">{{link_to('signature', 'Signatures') }}</div>
                    <div class="p-2 flex-fill">{{link_to('about', 'About Us') }}</div>
                    <div class="p-2 flex-fill">{{link_to('team', 'Our Team') }}</div>
                    <div class="p-2 flex-fill">{{link_to('vote', 'Suggestions')}}</div>
                    <div class="p-2 flex-fill"><a href="/">Help Desk</a></div>
                </div>

                <div class="social-icons mx-auto mt-5" style="max-width:200px;">
                    <div class="d-flex text-center">
                        <div class="p-2 flex-fill">
                            <a href="#" target="_blank">
                                <i class="fab fa-facebook fa-fw fa-2x"></i>
                            </a>
                        </div>
                        <div class="p-2 flex-fill">
                            <a href="https://twitter.com/maxcapedotcom" target="_blank">
                                <i class="fab fa-twitter fa-fw fa-2x"></i>
                            </a>
                        </div>
                        <div class="p-2 flex-fill">
                            <a href="https://discord.gg/JTTsNpa" target="_blank">
                                <i class="fab fa-discord fa-fw fa-2x"></i>
                            </a>
                        </div>
                    </div>
                </div>

                <div class="small text-center text-muted">
                    Copyright &copy; <?php echo date("Y"); ?> MaxCape. | All Rights Reserved - Runescape &copy; Jagex LTD. 1999-2018.<br>
                    <a href="" class="yellow-text">Terms of Service</a> | <a href="" class="yellow-text">Privacy Policy</a>
                </div>


            </div>

        </div>
    </div>
</footer>