<div class="row" style="padding-top:100px;padding-bottom:100px;">
    <div class="col-sm-12 text-center">
        <i class="fal fa-exclamation-circle fa-5x text-danger mb-2"></i>
        <h1>PROFILE PRIVATE</h1>
        <div class="small-divider"></div>
        <p class="text-secondary">The user your looking for has opted in for a private profile.</p>
        <p class="text-secondary">Press the back button or {{ link_to('', 'Return Home') }}</p>

        {{ content() }}
    </div>
</div>