<div class="row" style="padding-top:100px;padding-bottom:100px;">
    <div class="col-sm-12 text-center">
        <i class="fal fa-exclamation-circle fa-5x text-danger"></i>
        <h1>Page not Found</h1>
        <div class="small-divider"></div>
        <p class="text-secondary">Oh noes! It appears you've stumbled into the void, but don't worry...we can fix this...</p>
        <p class="text-secondary">Press the back button or {{ link_to('', 'Return Home') }}</p>

        {{ content() }}
    </div>
</div>