<div class="row" style="padding-top:100px;padding-bottom:100px;">
    <div class="col-sm-12 text-center">
        <i class="far fa-frown fa-5x text-danger"></i>
        <h1>Disabled Page</h1>
        <div class="small-divider"></div>
        <p class="text-secondary">This page is currently disabled. It will return in the future.</p>
        <p class="text-secondary">Sorry for the inconvenience.</p>

        {{ content() }}
    </div>
</div>