<div class="row" style="padding-top:100px;padding-bottom:100px;">
    <div class="col-sm-12 text-center">
        <i class="fal fa-exclamation-circle fa-5x text-danger"></i>
        <h1>Access Denied</h1>
        <div class="small-divider"></div>
        <p class="text-secondary">It appears you don't have access to this page...</p>
        <p class="text-secondary">{{ link_to('', 'Return Home') }}</p>
    </div>
</div>