<div class="row" style="padding-top:100px;padding-bottom:100px;">
    <div class="col-sm-12 text-center">
        <i class="far fa-frown fa-5x text-danger"></i>
        <h1>Server Error</h1>
        <div class="small-divider"></div>
        <p class="text-secondary">An error has occured in our script. Sorry about the inconvenience. Still a few bugs to work out ;)</p>
        <p class="text-secondary">Press the back button or {{ link_to('', 'Return Home') }}</p>

        {{ content() }}
    </div>
</div>