<div class="col-sm-12 col-lg-4">
    <div class="card border-0 shadow-sm mb-3">
        <div class="list-group">
            {{ link_to('admin', '<i class="fal fa-home fa-fw"></i> Dashboard Home', 'class' : 'list-group-item') }}
            {{ link_to('admin/news', '<i class="fal fa-newspaper fa-fw"></i> News System', 'class' : 'list-group-item') }}
            {{ link_to('admin/payments', '<i class="fal fa-dollar-sign fa-fw"></i> User Donations', 'class' : 'list-group-item') }}
            {{ link_to('admin/users', '<i class="fal fa-users fa-fw"></i> User List', 'class' : 'list-group-item') }}
        </div>
    </div>
</div>