{{ partial('bestiary/search') }}

<div class="row pb-5">
    <div class="col-sm-12 col-xl-3">
        <div class="card shadow-sm mb-3">
            <div class="card-body text-center">
                {{ image(imageUrl, 'style' : 'max-width:100%;max-height:200px') }}
            </div>
        </div>

        {% if beast.areas|json_decode(true)|count > 0 %}
        <div class="card shadow-sm mb-3">
            <table class="table table-hover table-striped mb-0">
                <thead>
                <tr>
                    <th>Areas Found</th>
                </tr>
                </thead>
                {% for value in beast.areas|json_decode(true) %}
                <tr>
                    <td style="width:200px;">{{ link_to('bestiary/area/'~value, value) }}</td>
                </tr>
                {% endfor %}
            </table>
        </div>
        {% endif %}

        <div class="card shadow-sm mb-3">
            <table class="table table-hover table-striped mb-0">
                {% for key, value in base_stats %}
                <tr>
                    <td style="width:200px;">{{ key }}</td>
                    <td>{{ value }}</td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>

    <div class="col-sm-12 col-xl-9">
        {{ content() }}

        {% if drop_tables is defined %}
            {% for table in drop_tables %}
                <div class="card shadow-sm mb-3">
                    <table class="table mb-0">
                        <thead>
                        <tr>
                            <th style="width: 400px;">Item Name</th>
                            <th style="width: 200px;">Drop Amount</th>
                            <th style="width: 200px;">Rarity</th>
                            <th style="width: 200px;" class="text-right">GE Price</th>
                        </tr>
                        </thead>
                    </table>
                    {{ table }}
                </div>
            {% endfor %}
        {% else %}

            <div class="alert alert-danger mb-0">
                This npc has no drops on record.
            </div>
        {% endif %}
        </div>
    </div>
</div>