<div class="row mt-5 mb-3">
    <div class="col-sm-12">
        <div class="card shadow-sm">
            <div class="card-body">
                {{ form('bestiary', 'method' : 'post') }}
                <div class="form-row">
                    <div class="col-10">
                        {{ text_field('search', 'class' : 'form-control', 'placeholder' : 'Search NPC by Name...') }}
                    </div>
                    <div class="col-2">
                        <button type="submit" class="btn btn-primary btn-block">
                            <i class="fal fa-search"></i>
                        </button>
                    </div>
                </div>
                {{ end_form() }}
            </div>
        </div>
    </div>
</div>