<div class="row my-5">
    <div class="col-sm-12 col-xl-12">
        <h3>About Us</h3>
        <hr>
        <p>Maxcape is a <a href="https://www.runescape.com">RuneScape</a> fansite and was originally founded by Evan(The Orange) in 2012. In 2017, Brian and Tyler took over ownership.</p>
        <p>As a fansite, Maxcape aims to provide a modern service that focuses on aiding RuneScape players in as many ways as possible. We aim to stay up to date with the latest developments
            within RuneScape itself, and to make any changes to our service as needed.</p>
        <p>Along with our service, our community and website endeavour is to make your stay a pleasant one. Our website is extensive and detailed on the information it provides, and we're always
            willing to make improvements to better serve our users. Our website is designed to aid any RuneScape player from a <u>beginner</u> all the way to an <u>expert</u> player.
            This whole website is maintained by a hard-working and active <a href="#">team</a>. As always, feedback from our users is greatly appreciated and helps us revise our website
            as needed. Corrections, comments, or complaints about any of our content can be posted within our <a href="https://discord.gg/JTTsNpa">discord</a> server.</p>
    </div>
</div>