<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<title>MaxCape</title>
	<meta name="keywords" content="RuneScape, Rune, Scape, Jagex, Jagex Games">
	<meta name="description" content="The most modern RuneScape tracking website.">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="shortcut icon" type="image/png" href="<?= base_url; ?>img/favicon.ico"/>

    {{ stylesheet_link("css/bootstrap.min.css") }}
    {{ stylesheet_link("css/bootstrap-custom.css") }}
    {{ stylesheet_link("css/fontawesome-all.css") }}
    {{ stylesheet_link("css/stylesheet.css") }}

    {% if cookies.has("theme_color") and cookies.get("theme_color")|in_array(constant("theme_colors")|array_keys) %}
    {{ stylesheet_link("css/colors/"~ cookies.get('theme_color') ~".css") }}
    {% else %}
    {{ stylesheet_link("css/colors/blue.css") }}
    {% endif %}

    {{ stylesheet_link("css/aos.css") }}

    {{ javascript_include("js/jquery-3.3.1.min.js") }}
    {{ javascript_include("js/popper.min.js") }}
    {{ javascript_include("js/bootstrap.min.js") }}
    {{ javascript_include("js/aos.js") }}
    {{ javascript_include("js/javascript.js") }}
    {% if router.getControllerName() is 'admin' %}
    {{ javascript_include("js/chart.min.js") }}
    {% endif %}

    {% if router.getControllerName() is 'designer' %}

    {{ javascript_include("js/designer/spectrum.js") }}
    {{ stylesheet_link("css/spectrum.css") }}

    {% endif %}
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-124556765-1"></script>
    <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-124556765-1');
</script>
</head>
<body>
    {% set controller = router.getControllerName() %}
    {% set action = router.getActionName() %}

    {% if controller is not 'login'
        and controller is not 'register'
        and controller is not 'recover' %}
    {{ partial('partials/header') }}
    {% endif %}

    <div class="content">
        <div class="container">
            {{ content() }}
        </div>
    </div>

    {% if controller is not 'login'
        and controller is not 'register'
        and controller is not 'recover' %}
    {{ partial('partials/footer') }}
    {% endif %}

</body>
</html>