<div class="row" style="padding-top:100px;padding-bottom:100px;">
    <div class="col-sm-12 text-center">
        <i class="fal fa-exclamation-circle fa-5x text-danger"></i>
        <h1>Slow Down!</h1>
        <div class="small-divider"></div>
        <p class="text-secondary">We can only handle so much. Slow down just a bit will ya? <3</p>
        <p class="text-secondary">Press the back button or {{ link_to('', 'Return Home') }}</p>

        {{ content() }}
    </div>
</div>